### PR TITLE
Use pyatmo scope list

### PR DESCRIPTION
**Pull request by cgtobi**
I switched back to using the pyatmo scope const since it make no sense to manage that list twice.
Also I made the tests pass and the linter happy. Great work and thanks for your contribution.

### CODE REVIEW

**Comment by deosrc** [comment]
> ...since it make no sense to manage that list twice.

While I agree managing a list of all scopes twice isn't right, I had changed it for 2 reasons:

- Upgrading the library caused the issue because new scopes were added which don't seem to be supported in this case. Having a static list would prevent new scopes creeping in which are easily missed when testing.
- Security and privacy best practice recommends that you only request the permissions (scopes) which you require. Currently we seem to be taking the approach of asking for access to everything which is functional.

So the change was intended to be to a move to request only the required scopes, not all functional scopes, however, I expect [I've changed too much for this fix](https://developers.home-assistant.io/docs/review-process/#creating-the-perfect-pr). Your change here minimises the changes and avoids a more complex discussion, so I'll get this in and a PR to the main core repo created. The change to explicitly list scopes I'll do as a separate PR (if I get around to it) so that it can have more thorough consideration without holding anything up. The `get_api_scopes` function should at least make this easier in future.

Thanks for this. I'll be sure to credit your work on the PR.

**Comment by deosrc** [comment]
@cgtobi Only just realised you're the code owner 😂 Let me know if you agree with my bullet points above. If not then I'll not bother with the scopes PR.

**Comment by cgtobi** [comment]
While I agree on keeping the minimal set of scopes it does not make sense in this context since we can't determine which scopes are actually needed. That's why I'd rather keep it in one place and only manage an "exclude" list for HA cloud.

**Comment by deosrc** [comment]
Not sure if you mean because we don't know what devices people want to control, or because we're not sure which scopes are required for the integration to function (it's much easier to build the list of scopes while adding functionality than it is to reduce it to only the required scopes later).

Either way, I'll leave it be. Good discussion. Thanks.

**Comment by cgtobi** [comment]
We don't know which devices a user has until we actually are connected and retrieve the data.

**Pull request merged**
